In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(4,3)
x

tensor(1.00000e-45 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  5.6052,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [4]:
y = torch.rand(4,3)
y

tensor([[ 0.6647,  0.7528,  0.7323],
        [ 0.9986,  0.2185,  0.0362],
        [ 0.8336,  0.6129,  0.6496],
        [ 0.4148,  0.6206,  0.1511]])

In [6]:
x = torch.zeros(5,3)
x

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [10]:
x = x.new_ones(2,3)
x

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [11]:
x.size()

torch.Size([2, 3])

In [13]:
x = torch.rand(2,3)
y = torch.zeros(2,3)
print(x)
print(y)

tensor([[ 0.5967,  0.8252,  0.5925],
        [ 0.5323,  0.7817,  0.5236]])
tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])


In [14]:
x+y

tensor([[ 0.5967,  0.8252,  0.5925],
        [ 0.5323,  0.7817,  0.5236]])

In [15]:
y = torch.rand(2,3)
print(y)
print(x+y)   

tensor([[ 0.8109,  0.8610,  0.6873],
        [ 0.2795,  0.4075,  0.1915]])
tensor([[ 1.4076,  1.6861,  1.2797],
        [ 0.8117,  1.1892,  0.7151]])


In [16]:
print(torch.add(x,y))  #another syntax.

tensor([[ 1.4076,  1.6861,  1.2797],
        [ 0.8117,  1.1892,  0.7151]])


In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.4076,  1.6861,  1.2797],
        [ 0.8117,  1.1892,  0.7151]])


In [18]:
y.add(x)

tensor([[ 1.4076,  1.6861,  1.2797],
        [ 0.8117,  1.1892,  0.7151]])

In [20]:
x[:,1]

tensor([ 0.8252,  0.7817])

In [21]:
x = torch.rand(4,4)
x

tensor([[ 0.7491,  0.3745,  0.4613,  0.8767],
        [ 0.1357,  0.8755,  0.7114,  0.3104],
        [ 0.3237,  0.6906,  0.5160,  0.1803],
        [ 0.6762,  0.0022,  0.7031,  0.7658]])

In [23]:
y = x.view(16)
y

tensor([ 0.7491,  0.3745,  0.4613,  0.8767,  0.1357,  0.8755,  0.7114,
         0.3104,  0.3237,  0.6906,  0.5160,  0.1803,  0.6762,  0.0022,
         0.7031,  0.7658])

In [24]:
z= x.view(-1,8)
z

tensor([[ 0.7491,  0.3745,  0.4613,  0.8767,  0.1357,  0.8755,  0.7114,
          0.3104],
        [ 0.3237,  0.6906,  0.5160,  0.1803,  0.6762,  0.0022,  0.7031,
          0.7658]])

In [26]:
print(z.size())
print(y.size())

torch.Size([2, 8])
torch.Size([16])


In [29]:
##### convert Torch to Numpy Array

a = torch.rand(3,3)
b = a.numpy()
print(a)
print(b)

tensor([[ 0.1333,  0.5551,  0.2016],
        [ 0.1889,  0.4824,  0.9500],
        [ 0.6161,  0.6830,  0.8263]])
[[0.13326383 0.5550761  0.20155913]
 [0.18886971 0.4823972  0.94998544]
 [0.61611867 0.68303484 0.82632715]]


In [31]:
#### convert Numpy to Torch

import numpy as np
a = np.ones(4)
b = torch.from_numpy(a)
b

tensor([ 1.,  1.,  1.,  1.], dtype=torch.float64)