In [1]:
import torch

In [2]:
# setting requires grad to true --> this will allow you to track all operations. then calling .backward() method will help in calculating gradients automatically


In [6]:
x = torch.ones(2,3,requires_grad=True)
x

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [8]:
y = x+2
y

tensor([[ 3.,  3.,  3.],
        [ 3.,  3.,  3.]])

In [10]:
print(y.grad_fn)

In [11]:
z = y*y*2
z

tensor([[ 18.,  18.,  18.],
        [ 18.,  18.,  18.]])

In [13]:
out = z.mean()
print(z,out)

tensor([[ 18.,  18.,  18.],
        [ 18.,  18.,  18.]]) tensor(18.)


In [15]:
a = torch.randn(2,2)
a

tensor([[-2.0204, -0.2037],
        [-1.4636, -0.3137]])

In [17]:
a = ((a * 3) / (a - 1))
print(a)

tensor([[ 5.9799, -3.0936],
        [ 6.8349, -7.5764]])


In [23]:
print(a.requires_grad)
print(x.requires_grad)
a.requires_grad_(True)  ## setting it to true
print(a.requires_grad)
b = a.sum()
print(b.grad_fn)

True
True
True


In [24]:
### LET US BACKPROPAGATE NOW
out.requires_grad

True

In [25]:
out.backward()

In [26]:
print(x.grad)

tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.]])


In [29]:
x = torch.randn(3, requires_grad=True)

y = x * 2
print(y)
print(y.data.norm())
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-1.7592,  4.8987, -0.3474])
tensor(5.2166)
tensor([ -450.3635,  1254.0726,   -88.9280])


In [35]:
print(x.requires_grad)  

True


In [36]:
# let us remove the auto grad option


with torch.no_grad():
    print((x ** 2).requires_grad)

False
